(ns q9-oracle
  "The Clojure side of the whole-component acceptance: run `aftership.main` under
   nbb and print the same numbers the aarch64 artifact prints.

     nbb --classpath src:<kotoba-lang/text>/src q9-oracle.cljs

   GENERATED by scripts/gen-parity-harness.cljs. Only the layers that are
   derivable from the oracle without a judgement call are here: the route
   count, and as-int / as-bool / page-limit over the shared fixture table.
   The store, filter, pagination, handler and expand layers need fixtures
   shaped to this repository's entities and are NOT generated -- an arm that
   runs without asserting anything about this repository is worse than an
   absent one.

   ## The control

   `as-int` of \"12abc\" MUST differ between this harness and the artifact.
   The oracle's as-int is a reader conditional whose branches disagree: the
   :cljs branch is js/parseInt and yields 12, the :clj branch is
   Long/parseLong which throws and yields 0, and the component matches :clj.
   Measured across the cohort and recorded in kotoba-lang
   lang/q9-wave1-tranche-1.edn.

   So a run of this harness under nbb in which EVERYTHING matches has not
   demonstrated that it can detect a mismatch, and is not a pass. A run on a
   JVM would legitimately agree on that row; say which runtime produced any
   result."
  (:require [aftership.main :as m]))

;; Byte-identical in every hand-written harness in this cohort.
(def fixture-text
  {0 "12" 1 " 42 " 2 "-7" 3 "12abc" 4 "" 5 "true" 6 "TRUE" 7 "Yes" 8 "on"
   9 "1" 10 "0" 11 "false" 12 "null" 13 "nope"})

(defn row [label v] (println (str label "\t" v)))

(println "; oracle = aftership.main under nbb")
(row "main(route-count)" (count m/routes))

(println "; as-int")
(doseq [i [0 1 2 3 4 12]] (row (str "as-int " i) (m/as-int (fixture-text i))))

(println "; as-bool")
(doseq [i [5 6 7 8 9 10 11 4 13]]
  (row (str "as-bool " i) (if (m/as-bool (fixture-text i)) 1 0)))

(println "; page-limit")
(doseq [r [-5 0 1 20 99 100 101 250]] (row (str "page-limit " r) (m/page-limit r)))
